# Generated by Django 4.2.7 on 2024-01-16 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('opt_1', models.CharField(max_length=120)),
                ('opt_2', models.CharField(max_length=120)),
                ('opt_3', models.CharField(max_length=120)),
                ('opt_4', models.CharField(max_length=120)),
                ('time', models.IntegerField()),
                ('right_answer', models.CharField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
