# Generated by Django 4.2.7 on 2024-01-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_usersubmittedanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubmittedanswer',
            old_name='right_answer',
            new_name='given_answer',
        ),
    ]
