# Generated by Django 4.2.7 on 2024-01-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_right_answer_usersubmittedanswer_given_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='markPerQuestion',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='totalQuestions',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
