# Generated by Django 4.2.7 on 2024-01-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_markperquestion_question_totalquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='markPerQuestion',
        ),
        migrations.RemoveField(
            model_name='question',
            name='totalQuestions',
        ),
    ]
