# Generated by Django 4.2.7 on 2024-01-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_image_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='exam_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
